name: folio

services:
  folio-postgres:
    image: postgres:17-alpine
    container_name: folio-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: folio
      POSTGRES_USER: folio
      POSTGRES_PASSWORD: F0li^o#
      TZ: Asia/Seoul
    volumes:
      - folio-pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  folio-pgdata:
    name: folio-pgdata
    driver: local
