version: '3.8'

services:
  folio-postgres:
    image: postgres:17-alpine
    container_name: folio-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      TZ: Asia/Seoul
    volumes:
      - folio-pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  folio-pgdata:
    driver: local
